# Generated by Django 3.1.2 on 2020-10-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='base_64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
