# Generated by Django 3.1.2 on 2020-10-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_image_remote_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='raw_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
