# Generated by Django 3.1.2 on 2020-10-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_image_raw_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='extension',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
